Repository sahib/rmlint, pull requests merged in 2025-03, with the labels that each got.

#691 json: properly escape cwd and args
  lib/formats/json.c
Labels: bug

#538 (Docs) Fix semantic typo
  docs/rmlint.1.rst
Labels: bug, topic-documentation

#603 Tests: replace nose with pytest
  docs/developers.rst
  docs/install.rst
  docs/testing.rst
  pytest.ini
  tests/SConscript
  tests/conftest.py
  tests/requirements.txt
  tests/test_formatters/test_csv.py
  tests/test_formatters/test_json.py
  tests/test_formatters/test_others.py
  tests/test_formatters/test_py.py
  tests/test_formatters/test_sh.py
  tests/test_mains/test_dedupe.py
  tests/test_mains/test_hash.py
  tests/test_mains/test_is_reflink.py
  tests/test_options/test_cache.py
  tests/test_options/test_clamp.py
  tests/test_options/test_color.py
  tests/test_options/test_equal.py
  tests/test_options/test_help.py
  tests/test_options/test_hidden_dirs.py
  tests/test_options/test_keep_hardlinks.py
  tests/test_options/test_km.py
  tests/test_options/test_match_basenames.py
  tests/test_options/test_match_with_extension.py
  tests/test_options/test_match_without_extension.py
  tests/test_options/test_merge_directories.py
  tests/test_options/test_mtime_window.py
  tests/test_options/test_newer_than.py
  tests/test_options/test_no_backup.py
  tests/test_options/test_pass_files.py
  tests/test_options/test_perms.py
  tests/test_options/test_rankby.py
  tests/test_options/test_replay.py
  tests/test_options/test_size.py
  tests/test_options/test_sorting.py
  tests/test_options/test_stdin.py
  tests/test_options/test_symlinks.py
  tests/test_robustness/test_8Mlongpathfiles.py
  tests/test_robustness/test_badlinks_as_args.py
  tests/test_robustness/test_bigfiles.py
  tests/test_robustness/test_collisions.py
  tests/test_robustness/test_manyfiles.py
  tests/test_robustness/test_manylongpathfiles.py
  tests/test_robustness/test_path_doubles.py
  tests/test_types/test_badlink.py
  tests/test_types/test_baduids.py
  tests/test_types/test_duplicate.py
  tests/test_types/test_empty_dirs.py
  tests/test_types/test_empty_files.py
  tests/test_types/test_nonstripped.py
  tests/utils.py
Labels: topic-testsuite

#568 Fixed manpage typo in rmlint jq pipe example
  docs/rmlint.1.rst
Labels: topic-documentation

#560 Fix a few typos and double-spacing in the man page
  docs/cautions.rst
  docs/faq.rst
  docs/rmlint.1.rst
Labels: topic-documentation

#591 Fix usages of single backticks to double backticks
  README.rst
  docs/rmlint.1.rst
  docs/testing.rst
  docs/translators.rst
  docs/tutorial.rst
Labels: topic-documentation

#695 chat
  README.rst
Labels: topic-documentation

#689 fix data-loss issue with replays w/o checksums
  lib/checksum.c
  lib/replay.c
  tests/test_options/test_replay.py
Labels: do-not-merge

#573 rmlint: fix the build on older Darwin systems
  lib/cmdline.h
  lib/traverse.c
  lib/traverse.h
Labels: topic-compiling

#728 Use proper paths for shell calls
  tests/test_formatters/test_sh.py
Labels: topic-testsuite
